services:
  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    image: wbtech_l0-consumer
    container_name: Consumer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - nats-streaming

  producer:
    build:
      context: .
      dockerfile: Producer/Dockerfile
    image: wbtech_l0-producer
    container_name: Producer
    depends_on:
      - nats-streaming
      - consumer

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  nats-streaming:
    image: nats-streaming